use-tabs: false

preset: none

enabled:
  - "binary_operator_spaces"
  - "blank_line_after_opening_tag"
  - "blank_line_before_break"
  - "blank_line_before_cases"
  - "blank_line_before_continue"
  - "blank_line_before_declare"
  - "blank_line_before_do"
  - "blank_line_before_exit"
  - "blank_line_before_for"
  - "blank_line_before_goto"
  - "blank_line_before_if"
  - "blank_line_before_include"
  - "blank_line_before_return"
  - "blank_line_before_switch"
  - "blank_line_before_throw"
  - "blank_line_before_try"
  - "blank_line_before_while"
  - "boolean_operator_linebreak_beginning"
  - "cast_spaces"
  - "class_definition"
  - "combine_consecutive_issets"
  - "combine_consecutive_unsets"
  - "compact_nullable_typehint"
  - "concat_with_spaces"
  - "const_separation"
  - "const_visibility_required"
  - "explicit_indirect_variable"
  - "function_declaration"
  - "function_typehint_space"
  - "indentation"
  - "short_array_syntax"
  - "short_list_syntax"
  - "lowercase_cast"
  - "lowercase_constants"
  - "lowercase_keywords"
  - "lowercase_static_reference"
  - "magic_constant_casing"
  - "magic_method_casing"
  - "method_argument_space"
  - "method_chaining_indentation"
  - "method_separation"
  - "method_visibility_required"
  - "multiline_comment_opening_closing"
  - "native_function_casing"
  - "native_function_type_declaration_casing"
  - "new_with_braces"
  - "newline_before_semicolons_chained"
  - "no_alternative_syntax"
  - "no_binary_string"
  - "no_blank_lines_after_phpdoc"
  - "no_closing_tag"
  - "no_empty_comment"
  - "no_empty_phpdoc"
  - "no_empty_statement"
  - "no_extra_block_blank_lines"
  - "no_extra_consecutive_blank_lines"
  - "no_multiline_whitespace_around_double_arrow"
  - "no_null_property_initialization"
  - "no_short_bool_cast"
  - "no_single_line_asterisk_comment"
  - "no_singleline_whitespace_before_semicolons"
  - "no_spaces_after_function_name"
  - "no_spaces_inside_offset"
  - "no_spaces_inside_parenthesis"
  - "no_spaces_outside_offset"
  - "no_superfluous_elseif"
  - "no_trailing_comma_in_list_call"
  - "no_trailing_comma_in_singleline_array"
  - "no_trailing_whitespace"
  - "no_trailing_whitespace_in_comment"
  - "no_unset_cast"
  - "no_useless_else"
  - "no_useless_return"
  - "no_whitespace_before_comma_in_array"
  - "normalize_index_brace"
  - "not_operator_with_successor_space"
  - "object_operator_without_whitespace"
  - "phpdoc_align"
  - "phpdoc_indent"
  - "phpdoc_link_to_see"
  - "phpdoc_to_comment"
  - "phpdoc_types"
  - "post_increment"
  - "print_to_echo"
  - "property_separation"
  - "property_visibility_required"
  - "protected_to_private"
  - "return_assignment"
  - "return_type_declaration"
  - "self_static_accessor"
  - "semicolon_after_instruction"
  - "single_blank_line_at_eof"
  - "single_line_class_definition"
  - "single_line_throw"
  - "single_quote"
  - "single_space_after_construct"
  - "space_after_semicolon"
  - "standardize_increment"
  - "standardize_not_equals"
  - "switch_case_semicolon_to_colon"
  - "switch_case_space"
  - "ternary_operator_spaces"
  - "trim_array_spaces"
  - "unalign_double_arrow"
  - "unalign_equals"
  - "unary_operator_spaces"

finder:
  exclude:
    - "core/assets"
    - "core/includes"