name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: password
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: '8.3'
          extensions: mbstring, dom, fileinfo, mysql
    - name: Start mysql service
      run: sudo /etc/init.d/mysql start
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
    - name: Build assets
      run: npm install && npm run build
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Run Migration
      run: php artisan migrate -v
    - name: Execute tests via PHPUnit
      run: vendor/bin/phpunit
      env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
